### ISSUE TITLE
Badly packaged library

### ISSUE THREAD

**Issue by simpsojo** [bergben/ng2-pica#10]
I started getting the following error after upgrading to Angular 6.1.0 (CLI 6.1.0)

> ERROR in ./node_modules/ng2-pica/ng2-pica.ts
> Module build failed: Error: C:\git\xyz\node_modules\ng2-pica\ng2-pica.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
>     at AngularCompilerPlugin.getCompiledFile (C:\git\xyz\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
>     at plugin.done.then (C:\git\xyz\node_modules\@ngtools\webpack\src\loader.js:41:31)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

I use ng2-img-tools which depends on ng2-pica.  This is a showstopper for me :(

I saw that node_modules/ng2-pica/dist doesn't contain any javascript.  I tried to build it myself without success ( Error: Could not resolve './src/ng2-pica.service' from dist\ng2-pica.js -- because it isn't there).

Any help/pointers would be greatly appreciated !

Many thanks

**Comment by bergben** [comment]
Should be fixed now!
