### ISSUE TITLE
Resizing a PNG image without alpha channel produces a JPG image

### ISSUE THREAD

**Issue by Ivan-Perez** [bergben/ng2-pica#2]
Hi!

I'm using this library to resize images, and I've detected that when I resize a PNG image that has no alpha channel I get a JPG image. 

Looking at the code, I see why this is happening: https://github.com/bergben/ng2-pica/blob/master/src/ng2-pica.service.ts#L97. Why is this implemented this way? Shouldn't that condition be `if (file.type === "image/jpeg")` so the format from the original image is left unchanged?

Thanks in advance!

**Comment by bergben** [comment]
Hi @Ivan-Perez  :) 

I just fixed this in 1.0.7, see https://github.com/bergben/ng2-pica/commit/9bbb8055f218799ec9117a451a2de84ad7fd3a64

**Comment by Ivan-Perez** [comment]
Thanks!
