### ISSUE TITLE
Import pica dist file directly

### ISSUE THREAD

**Issue by awerlang** [bergben/ng2-pica#3]
Hey, just a tip. Instead of maintaing a separate fork of `pica`, have you tried:

```
import ImageResizer from 'pica/dist/pica';
```

Rollup seems to be okay with that.

In time, I'm not sure why a wrapper service is needed at all.

**Comment by bergben** [comment]
Hey there @awerlang,

as far as I remember back when I created ng2-pica it wouldn't work without forking it and removing some parts as described in the ReadMe of my pica fork: 
https://github.com/bergben/pica/blob/master/README.md

Maybe it would work now though.

**Comment by awerlang** [comment]
If by node.js support you're refering to `require(...)` that works okay. I also had issues with it but this was the simplest workaround I could think of. But yeah, I see the source looked a bit different when you started.

Feel free to close the issue.

**Comment by bergben** [comment]
I think it would be good to try again if it works now with the original repo as that would be a better solution indeed. I'll leave this issue open and maybe someone comes along who wants to contribute for whom this would be a good point to start :D

**Comment by bergben** [comment]
I just fixed this in version 1.1.0 👍
