### ISSUE TITLE
provide index.ts for importing

### ISSUE THREAD

**Issue by maku** [bergben/ng2-pica#5]
It would be really convenient when you are able to provide an index.ts file which exports anything from the library so you can write: 

```
import {Ng2PicaService, resizeCanvasOptions} from 'ng2-pica';
```

instead of:

```
import {Ng2PicaService} from 'ng2-pica/dist/ng2-pica';
import {resizeCanvasOptions} from 'ng2-pica/dist/src/ng2-pica.service';
```

**Comment by bergben** [comment]
Thanks for reporting this issue @maku , it is fixed in 1.2.0
